---
- name: Installer Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes
  notify: redemarrer_nginx

- name: Configurer Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: redemarrer_nginx